### ISSUE TITLE
Unable to retain the private ip address addition

### ISSUE THREAD

**Issue by ragingdave** [livinginthepast/ipaddr_extensions#3]
Perhaps this is something in my setup, but on subsequent unattended runs on machines in a linode environment, the private ip address of the box is not added to the ohai attributes causing modification of (at least in my recipe set) firewall rules to be updated and inter-machine communication to fail. I will be adding an issue as well to chef itself as the 'cloud' or 'cloud_v2' ohai attributes aren't working either and only show the public address which could be the cause here as well.

That being said, looking through the network ohai attribute, I can see all the attributes including the public and private ip addresses so I'm not sure what is going on here.

**Comment by sax** [comment]
I wonder if there's something different between you attended and unattended chef runs. Maybe you can print out the ohai attributes from within the chef run, and look at the logs for an unattended run to see if there's a difference?

I know that a lot has changed within chef and within ohai since I wrote this code (I haven't used Chef for work in about a year and a half), so there's a good possibility that if you're using a newer version of either that something is different in the way dependent gems are loaded. Also, this does some "clever" things to try to get the `ipaddr_extensions` gem into the Chef runtime early enough for it to be available to ohai. It's very possible that something in rubygems has changed in a way that gets the gem loaded on the first run, but does not on subsequent runs.

**Comment by sax** [comment]
@ragingdave were you able to get anywhere with this issue? Is this an issue with chef or ohai, or is the ipaddr_extensions cookbook contributing to the problem?

**Comment by ragingdave** [comment]
At this point, I'm not sure and the resolution might be just using this extension and manually configuring firewalls rather than automated handling.

My use case involved querying chef for servers and getting the ohai attributes to generate private ip based firewall rules. This made it so connectivity would fluctuate based on what was reported to the chef server in ohai, which sometimes did/didn't have the private ip address attribute.

I currently did uncover an issue where my haproxy server wasn't able to submit ohai reports, which made it so chef didn't actually update the attributes so that could have been the cause. At this point I'm not even sure chef is the right solution, so I'll close this ticket since it's at least working now.

**Comment by sax** [comment]
Ok, thanks for the update. I've found that for my own infrastructure, once everything is converging and reporting correctly I never ran into issues with missing attributes. I would suspect that reporting issue is a strong suspect, especially if you see the private ip info on your haproxy nodes but not on other nodes.
